<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Runner;

/**
 * ContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForRunner(Runner $runner){
        return $this->createQueryBuilder('c')
                ->join('c.races', 'r')
                ->join('r.raceRunners', 'rr')
                ->where('rr.runner = :runner')
                ->setParameter('runner', $runner)
                ->getQuery()
                ->getResult();
    }
}
