<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Race;

/**
 * RaceRunnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRunnerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextStartNumber(Race $race){
        $maxNb = $this->createQueryBuilder('rr')
            ->select('max(rr.startNumber)')
            ->where('rr.race = :race')
            ->setParameter('race', $race)
            ->getQuery()
            ->getArrayResult()[0][1];

        return $maxNb ? $maxNb+1 : 1;
    }
}
