<?php

namespace AppBundle\Repository;

/**
 * RaceRunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRunRepository extends \Doctrine\ORM\EntityRepository
{
}
