<?php

namespace AppBundle\Repository;

/**
 * RaceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
