<?php

namespace AppBundle\Repository;

/**
 * RunnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RunnerRepository extends \Doctrine\ORM\EntityRepository
{
}
