<?php

namespace AppBundle\Repository;

/**
 * TrackPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackPointRepository extends \Doctrine\ORM\EntityRepository
{
}
