# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        nowrace_users:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: after_login

#            guard:
#              entry_point: netins.security.login_form_authenticator
#              authenticators:
#                - nowrace.security.login_form_authenticator
            logout:
              invalidate_session: false
              path: /logout
              target: /login